version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: hotel_reservation_db
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: hotel_reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

  app:
    build: .
    container_name: hotel_reservation_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotel_reservation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - postgres

volumes:
  postgresql-volume: